# Generated by Django 4.1.5 on 2023-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpLeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100, null=True)),
                ('employeeId', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('reasonForLeave', models.TextField(null=True)),
                ('employeeStatus', models.CharField(default='absent', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTimeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100, null=True)),
                ('employeeId', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('employeeTimeIn', models.TimeField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTimeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100, null=True)),
                ('employeeId', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('employeeTimeOut', models.TimeField(default=0, null=True)),
                ('employeeWorkDescription', models.TextField(null=True)),
                ('employeeStatus', models.CharField(default='present', max_length=50)),
            ],
        ),
    ]
