# Generated by Django 4.1.5 on 2023-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetimeout',
            name='employeeStatus',
            field=models.CharField(default='present', max_length=50),
        ),
    ]
