# Generated by Django 4.1.5 on 2023-12-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='userName',
            field=models.CharField(max_length=10),
        ),
    ]
