# Generated by Django 4.1.5 on 2023-01-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fatherName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(max_length=64),
        ),
    ]
